services:
  mariadb:
    image: mariadb:${MARIADB_VERSION}
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MARIADB_AUTO_UPGRADE=true
    volumes:
      - mariadb_data:/var/lib/mysql
      - certs_data:/etc/mysql/certs
      - ./mariadb.cnf:/etc/mysql/conf.d/ssl.cnf:ro
    expose:
      - 3306

  phpmyadmin:
    image: phpmyadmin:${PHPMYADMIN_VERSION}
    environment:
      - PMA_USER=root
      - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - PMA_HOST=mariadb
      - PMA_PORT=3306
      - UPLOAD_LIMIT=1g
    ports:
      - "8080:80"
    depends_on:
      - mariadb

  cert-manager:
    image: finalgene/openssh:${OPENSSH_VERSION}
    volumes:
      - certs_data:/app

  maven:
    image: maven:${MAVEN_VERSION}
    working_dir: /usr/srv/AppJava
    volumes:
      - maven_data:/root/.m2
      - ./AppJava:/usr/srv/AppJava
      - certs_data:/certs:ro

volumes:
  mariadb_data:
  certs_data:
  maven_data:
